export const CART_LOAD_ITEMS = 'CART_LOAD_ITEMS';
export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const CART_UPDATE_ITEM = 'CART_UPDATE_ITEM';
export const CART_RELOAD = 'CART_RELOAD';
